-- Seeding 9 Sample Courses

INSERT INTO "Course" (
    id, title, description, instructor, link, "imageUrl", platform, rating, lessons, duration, featured, level, language, category, "priceLabel", "priceMin", "priceMax", "learningPoints"
) VALUES 
-- 1. Crypto Masterclass (English, High Ticket)
(
    'crypto-master-2025',
    'Crypto Trading Masterclass 2025',
    'The ultimate guide to Bitcoin, Ethereum and Altcoin trading. Master technical analysis and on-chain data.',
    'Alex Hormozi',
    'https://example.com/crypto1',
    'https://images.unsplash.com/photo-1518546305927-5a440bbabb91?w=800&q=80',
    'Teachable',
    4.9,
    null,
    '12h 30m',
    true,
    'All Levels',
    'English',
    'Crypto',
    '$497',
    497,
    null,
    '["Blockchain Fundamentals", "Advanced Technical Analysis", "Risk Management"]'::jsonb
),
-- 2. Forex Zero to Hero (Spanish, Mid Ticket)
(
    'forex-zero-hero',
    'Forex de Cero a Rentable',
    'Aprende a operar el mercado de divisas sin indicadores. Acción del precio pura y estructura de mercado.',
    'Juan Trading',
    'https://example.com/forex1',
    'https://images.unsplash.com/photo-1611974765270-ca1258634369?w=800&q=80',
    'Hotmart',
    4.7,
    null,
    '8h',
    true,
    'Beginner',
    'Spanish',
    'Forex',
    '$297',
    297,
    null,
    '["Estructura de Mercado", "Psicología del Trading", "Gestión de Capital"]'::jsonb
),
-- 3. ICT Concepts (English, Free)
(
    'ict- mentorship',
    'ICT Inner Circle Trader Concepts',
    'Deep dive into Smart Money Concepts (SMC). Learn to trade like the institutions with liquidity and fair value gaps.',
    'Michael J. Huddleston',
    'https://youtube.com',
    'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=800&q=80',
    'YouTube',
    5.0,
    null,
    '40h+',
    false,
    'Advanced',
    'English',
    'Futures',
    'Free',
    0,
    null,
    '["Order Blocks", "Fair Value Gaps", "Liquidity Runs"]'::jsonb
),
-- 4. Futures Scalping (English, Subscription Range)
(
    'futures-scalping',
    'Naked Trading & Futures Scalping',
    'High frequency scalping strategies for S&P 500 and Nasdaq futures. No indicators, just price.',
    'Tom Dante',
    'https://example.com/futures1',
    'https://images.unsplash.com/photo-1611974765270-ca1258634369?w=800&q=80',
    'Vimeo',
    4.8,
    null,
    '15h',
    false,
    'Advanced',
    'English',
    'Futures',
    '$49/mo',
    49,
    null,
    '["DOM Reading", "Volume Profile", "Execution Speed"]'::jsonb
),
-- 5. Estrategias de Opciones (Spanish, Cheap)
(
    'opciones-financieras',
    'Dominando las Opciones Financieras',
    'Genera ingresos pasivos vendiendo opciones. Iron Condors, Butterflies y más.',
    'Maria Inversiones',
    'https://example.com/options1',
    'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&q=80',
    'Udemy',
    4.6,
    null,
    '6h',
    false,
    'Intermediate',
    'Spanish',
    'Options',
    '$29',
    29,
    null,
    '["Venta de Puts", "Covered Calls", "Gestión de Griegas"]'::jsonb
),
-- 6. Algorithmic Trading Python (English, Expensive)
(
    'algo-trading-python',
    'Algorithmic Trading with Python',
    'Build and deploy your own trading bots using Python, Pandas, and Backtrader.',
    'Tech Trader',
    'https://example.com/algo1',
    'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&q=80',
    'Coursera',
    4.9,
    null,
    '25h',
    true,
    'Advanced',
    'English',
    'Stocks',
    '$997',
    997,
    null,
    '["Python Backtesting", "API Integration", "Bot Deployment"]'::jsonb
),
-- 7. Psicología del Trading (Spanish, Ebook/Course)
(
    'psicologia-trading',
    'Psicología y Gestión Emocional',
    'El 90% del trading es mental. Aprende a controlar el FOMO, la ira y la euforia.',
    'Dr. Trading',
    'https://example.com/psych',
    'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&q=80',
    'Teachable',
    4.5,
    null,
    '4h',
    false,
    'All Levels',
    'Spanish',
    'General',
    '$47',
    47,
    null,
    '["Mindfulness", "Diario de Trading", "Rutinas de Alto Rendimiento"]'::jsonb
),
-- 8. Swing Trading Stocks (English, Mid)
(
    'swing-stocks',
    'Swing Trading Growth Stocks',
    'Catch the meat of the move. CANSLIM methodology and trend following for US Stocks.',
    'Mark Minervini Style',
    'https://example.com/stocks1',
    'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&q=80',
    'Private',
    4.8,
    null,
    '10h',
    false,
    'Intermediate',
    'English',
    'Stocks',
    '$497',
    497,
    null,
    '["VCP Patterns", "Risk/Reward", "Portfolio Management"]'::jsonb
),
-- 9. Smart Money en Español (Spanish, Free/Range)
(
    'smc-espanol',
    'Conceptos Smart Money (SMC) en Español',
    'Todo lo que necesitas saber sobre SMC explicado en tu idioma. Order blocks y liquidez.',
    'Pedro FX',
    'https://youtube.com',
    'https://images.unsplash.com/photo-1611974765270-ca1258634369?w=800&q=80',
    'YouTube',
    4.9,
    null,
    '12h',
    true,
    'Advanced',
    'Spanish',
    'Forex',
    'Gratis',
    0,
    null,
    '["Rangos Asiáticos", "Killzones", "Estructura Fractal"]'::jsonb
);
